DATASETS:
  MAKEHUMAN:
    SUBPATH:
    - makehuman_2954_tagp_ta_grid_20211117
  NAMES: ("MakeHuman", )
  TESTS: ("GRID", )
OUTPUT_DIR: logs/TAGPerson/01_direct_transfer/tagp_ta/tagp_ta_grid
_BASE_: ../../TAGPerson_base.yml
