DATASETS:
  MAKEHUMAN:
    SUBPATH:
    - makehuman_2954_tagp_ta_market_20211117
  NAMES: ("MakeHuman", )
  TESTS: ("Market1501", )
OUTPUT_DIR: logs/TAGPerson/01_direct_transfer/tagp_ta/tagp_ta_market
_BASE_: ../../TAGPerson_base.yml
