# encoding: utf-8
"""
anonymous
anonymous
"""

from fastreid.config import CfgNode as CN


def add_reattribute_config(cfg):

    _C = cfg

    # Camera
    _C.DATASETS.MARKET_CAMERA = CN()
    _C.DATASETS.MARKET_CAMERA.SUBPATH = ['']

    _C.DATASETS.MAKEHUMAN_ATTR = CN()
    _C.DATASETS.MAKEHUMAN_ATTR.OPTIONS = []
    # options should be: [{'option_name': 'xxx', }]


    _C.MODEL.ATTRIBUTE_HEADS = []
    _C.MODEL.OPTION_HEADS = []

    _C.MODEL.LOSSES.ATTRIBUTE = CN()
    _C.MODEL.LOSSES.ATTRIBUTE.ENABLED = False

    _C.MODEL.LOSSES.TRI.WEIGHTED_V1 = False

    _C.MODEL.LOSSES.OPTION = CN({"ENABLED": False})

    _C.MODEL.LOSSES.EXPAND_CAMERA = CN()
    _C.MODEL.LOSSES.EXPAND_CAMERA.ENABLED = False
    _C.MODEL.LOSSES.EXPAND_CAMERA.NAME = ("CrossEntropyLoss",)
    _C.MODEL.LOSSES.EXPAND_CAMERA.CE = CN()
    _C.MODEL.LOSSES.EXPAND_CAMERA.CE.EPSILON = 0.0
    _C.MODEL.LOSSES.EXPAND_CAMERA.CE.ALPHA = 0.2
    _C.MODEL.LOSSES.EXPAND_CAMERA.CE.SCALE = 1.0
    _C.MODEL.LOSSES.EXPAND_CAMERA.TRI = CN()
    _C.MODEL.LOSSES.EXPAND_CAMERA.TRI.MARGIN = 0.3
    _C.MODEL.LOSSES.EXPAND_CAMERA.TRI.NORM_FEAT = False
    _C.MODEL.LOSSES.EXPAND_CAMERA.TRI.HARD_MINING = False
    _C.MODEL.LOSSES.EXPAND_CAMERA.TRI.SCALE = 1.0
    _C.MODEL.LOSSES.EXPAND_CAMERA.TRI.USE_LINE = False # TODO: modify to True


    _C.DATALOADER.HARD_EXAMPLE_SAMPLER = False
    _C.DATALOADER.NUM_INSTANCE_IN_MESH_GROUP = 4

    _C.DATALOADER.BACKGROUND_SAMPLER = False
    _C.DATALOADER.NUM_INSTANCE_IN_BACKGROUND_GROUP = 4

    # Sampler
    _C.DATALOADER.EXPAND_NAIVE_IDENTITY_SAMPLER = CN()
    _C.DATALOADER.EXPAND_NAIVE_IDENTITY_SAMPLER.CAMERA = CN()
    _C.DATALOADER.EXPAND_NAIVE_IDENTITY_SAMPLER.CAMERA.ENABLED = False
    
    _C.DATALOADER.RESOLUTION_BALANCE_SAMPLER = CN()
    _C.DATALOADER.RESOLUTION_BALANCE_SAMPLER.NUM_RESOLUTION_PER_BATCH = 4



    _C.TEST.ATTRIBUTE = CN()
    _C.TEST.ATTRIBUTE.ENABLED = False
    _C.TEST.ATTRIBUTE.EVAL_ONE_ATTRIBUTE = False
    _C.TEST.ATTRIBUTE.ATTRIBUTE_HEAD_INDEX = 0
    
    return cfg
