DATASETS:
  MAKEHUMAN:
    SUBPATH:
    - makehuman_2954_tagp_tag_c_msmt_20211117
  NAMES: ("MakeHuman", )
  TESTS: ("MSMT17", )
OUTPUT_DIR: logs/TAGPerson/03_ablation_ta/03_01_tag_c/03_01_02_tag_c_msmt
_BASE_: ../../TAGPerson_base.yml
