DATASETS:
  MAKEHUMAN:
    SUBPATH:
    - makehuman_2954_tagp_tag_c_market_20211117
  NAMES: ("MakeHuman", )
  TESTS: ("Market1501", )
OUTPUT_DIR: logs/TAGPerson/03_ablation_ta/03_01_tag_c/03_01_01_tag_c_market
_BASE_: ../../TAGPerson_base.yml
