DATASETS:
  MAKEHUMAN:
    SUBPATH:
    - makehuman_2954_tagp_base_20211117
  NAMES: ("MakeHuman", )
  TESTS: ("Market1501", "MSMT17", "GRID")
OUTPUT_DIR: logs/TAGPerson/01_direct_transfer/tagp_base
SOLVER:
  CHECKPOINT_PERIOD: 80
TEST:
  EVAL_PERIOD: 80
_BASE_: ../TAGPerson_base.yml
