DATASETS:
  MAKEHUMAN:
    SUBPATH:
    - makehuman_2954_tagp_no_wc_fix_camera_elev_fixed_pose
  NAMES: ("MakeHuman", )
  TESTS: ("Market1501",)
OUTPUT_DIR: logs/TAGPerson/02_ablation_rendering_options/04_no_wc_fix_camera_elev_fixed_pose
SOLVER:
  CHECKPOINT_PERIOD: 100
TEST:
  EVAL_PERIOD: 100
_BASE_: ../TAGPerson_base.yml
