DATASETS:
  MAKEHUMAN:
    SUBPATH:
    - makehuman_2954_tagp_no_wc_fix_camera_elev
  NAMES: ("MakeHuman", )
  TESTS: ("Market1501",)
OUTPUT_DIR: logs/TAGPerson/02_ablation_rendering_options/05_no_wc_fix_camera_elev
_BASE_: ../TAGPerson_base.yml
