DATASETS:
  MAKEHUMAN:
    SUBPATH:
    - makehuman_2954_tagp_no_wc
  NAMES: ("MakeHuman", )
  TESTS: ("Market1501",)
OUTPUT_DIR: logs/TAGPerson/02_ablation_rendering_options/06_no_wc
_BASE_: ../TAGPerson_base.yml
