DATASETS:
  MAKEHUMAN:
    SUBPATH:
    - makehuman_2954_tagp_tag_g_market_20211117
  NAMES: ("MakeHuman", )
  TESTS: ("Market1501", )
OUTPUT_DIR: logs/TAGPerson/03_ablation_ta/03_02_tag_g/03_02_01_tag_g_market
_BASE_: ../../TAGPerson_base.yml
