DATASETS:
  MAKEHUMAN:
    SUBPATH:
    - makehuman_2954_tagp_tag_g_grid_20211117
  NAMES: ("MakeHuman", )
  TESTS: ("GRID", )
OUTPUT_DIR: logs/TAGPerson/03_ablation_ta/03_02_tag_g/03_02_03_tag_g_grid
_BASE_: ../../TAGPerson_base.yml
