DATASETS:
  MAKEHUMAN:
    SUBPATH:
    - makehuman_2954_tagp_tag_g_msmt_20211117
  NAMES: ("MakeHuman", )
  TESTS: ("MSMT17", )
OUTPUT_DIR: logs/TAGPerson/03_ablation_ta/03_02_tag_g/03_02_02_tag_g_msmt
_BASE_: ../../TAGPerson_base.yml
